wallets:
  - TNPdqto8HiuMzoG7Vv9wyyYhWzCojLeHAF  # Binance-4
  - TU4vEruvZwLLkSfV9bNw12EJTPvNr7Pvaa  # Bybit
  - TWpqsYjAw7rFPmWeZcwKQanCS6Kk8f5dhT  # BitPanda Express
  - TFTWNgDBkQ5wQoP8RXpRznnHvAVV8x5jLu  # HTX-4