-- ===============================================================
-- SCRIPT DE CREACIÓN DE LA VISTA ALERT_RULES_VIEW
-- Proyecto: TronScan Monitoring Pipeline
-- Autor: Yeison Alvarez Balvin
-- Fecha: 2025-10-06
-- ===============================================================
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_TRON_WH;
USE DATABASE TRON_SCAN_MONITORING;
USE SCHEMA TRANSACTIONS;

CREATE OR REPLACE VIEW ALERT_RULES_VIEW AS
SELECT
  ALERT_ID,
  RULE_NAME,
  WALLET,
  PERIOD,
  METRIC_VALUE,
  THRESHOLD,
  STATUS,
  ALERT_TIME
FROM ALERT_RULES_LOG
WHERE ALERT_TIME >= DATEADD(hour, -1, CURRENT_TIMESTAMP())
ORDER BY ALERT_TIME DESC;
