USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_TRON_WH;
USE DATABASE TRON_SCAN_MONITORING;
USE SCHEMA TRANSACTIONS;

CREATE OR REPLACE TABLE ALERT_RULES_LOG (
    ALERT_ID INT AUTOINCREMENT,
    RULE_NAME STRING,
    WALLET STRING,
    PERIOD STRING,
    METRIC_VALUE FLOAT,
    THRESHOLD FLOAT,
    STATUS STRING,
    ALERT_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
