USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_TRON_WH;
USE DATABASE TRON_SCAN_MONITORING;
USE SCHEMA TRANSACTIONS;

CREATE OR REPLACE TABLE WALLET_METRICS_HIST AS
SELECT 
    *,
    CURRENT_TIMESTAMP() AS SNAPSHOT_TS
FROM WALLET_METRICS
WHERE 1 = 0;