USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_TRON_WH;
USE DATABASE TRON_SCAN_MONITORING;
USE SCHEMA TRANSACTIONS;

CREATE OR REPLACE TASK CHECK_WALLET_RULES_TASK
  WAREHOUSE = COMPUTE_TRON_WH
  SCHEDULE = '15 MINUTE'
AS
  CALL CHECK_WALLET_RULES();
