USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_TRON_WH;
USE DATABASE TRON_SCAN_MONITORING;
USE SCHEMA TRANSACTIONS;

CREATE OR REPLACE PROCEDURE CHECK_WALLET_RULES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

  -- Regla 1: más de N transacciones en 7 días
  INSERT INTO ALERT_RULES_LOG (RULE_NAME, WALLET, PERIOD, METRIC_VALUE, THRESHOLD, STATUS)
  SELECT
      'Transaction Count Rule',
      OBSERVED_WALLET,
      '7 days',
      COUNT(*) AS METRIC_VALUE,
      100 AS THRESHOLD,
      CASE WHEN COUNT(*) > 100 THEN 'ALERT' ELSE 'OK' END
  FROM TRANSACTIONS
  WHERE TIMESTAMP_UTC >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  GROUP BY OBSERVED_WALLET
  HAVING COUNT(*) > 100;

  -- Regla 2: monto mayor que X en 7 días
  INSERT INTO ALERT_RULES_LOG (RULE_NAME, WALLET, PERIOD, METRIC_VALUE, THRESHOLD, STATUS)
  SELECT
      'Transaction Volume Rule',
      OBSERVED_WALLET,
      '7 days',
      SUM(AMOUNT) AS METRIC_VALUE,
      500000 AS THRESHOLD,
      CASE WHEN SUM(AMOUNT) > 500000 THEN 'ALERT' ELSE 'OK' END
  FROM TRANSACTIONS
  WHERE TIMESTAMP_UTC >= DATEADD(day, -7, CURRENT_TIMESTAMP())
  GROUP BY OBSERVED_WALLET
  HAVING SUM(AMOUNT) > 500000;
END;
$$;

